### ISSUE TITLE
Collinearity in basis_matrix and weird results for extreme outlier

### ISSUE THREAD

**Issue by SvenLorenz** [tidyfun/tidyfun#100]
Following example is giving me trouble:

```r
set.seed(1234)
f <- function(t) 2*t + dbeta(t, 5, 7) * ifelse(t < .5, -1, 1) - .2 * dnorm(t, 0.2, 0.05)

woo_out <- data.frame(id = rep(1:100, each = 251), 
                      arg = rep(c(seq(0, 1, l = 250),1.5), 100))
woo_out <- woo_out %>% mutate(data = f(arg) + rnorm(nrow(woo_out), sd = .5))

woo_tfb_out <- tfb_wavelet(woo_out, level = 5, filter_number = 3)
plot(tfd(woo_out), col = 2)
lines(woo_tfb_out)
```

![](https://user-images.githubusercontent.com/43496748/69860900-79243880-1297-11ea-97a4-b0e7fcc4d947.jpeg)

Several problems arose from adding an extreme outlier:
1. The basis matrix computes, for one column, only values not equal to zero for args that we interpolated and are not on the original grid. So when we bring the matrix back to the original grid every value is equal to zero and so `scale()` will output a column with only NA's in it.

2. After removing the NA column `lsfit()` gives a warning that the matrix is collinear.

3. The fit is really bad. 

This problem instantly goes away if i remove the `1.5` from `arg`. Also higher `filter_number` values make the estimates somewhat believable. In this example this at `filter_number = 6`, `lsfit()` also doesn't give a warning about collinearity then.

**Comment by fabian-s** [comment]
see the diffs for a41cf26. 

fits become better for higher levels, this might be something due to the interpolation of the grid, not sure:
with 
```r
woo_out <- woo_out %>% mutate(data = f(arg) + rnorm(nrow(woo_out), sd = .001))
woo_tfd <- tfd(woo_out)
woo_tfb_out <- tfb_wavelet(woo_out, level = 7, filter_number = 3)
plot(tfd(woo_out), col = 2)
lines(woo_tfb_out)
```
![image](https://user-images.githubusercontent.com/998541/69869643-b09ddf80-12ad-11ea-811e-077c9639fcee.png)

with `level = 3`:
![image](https://user-images.githubusercontent.com/998541/69869669-c90dfa00-12ad-11ea-8427-b5c58113d844.png)
