### ISSUE TITLE
empty names for `tf` vectors

### ISSUE THREAD

**Issue by jeff-goldsmith** [tidyfun/tidyfun#102]
There's an ongoing debate over at the `vctrs` camp about whether to allow `""` as a name for vector elements -- see [here](https://github.com/r-lib/vctrs/issues/780) and [here](https://github.com/r-lib/vctrs/pull/784). 

Right now, that's not allowed, which leads to a whole bunch of issues, including those below:

``` r
library(tidyfun)
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2
#> 
#> Attaching package: 'tidyfun'
#> The following objects are masked from 'package:stats':
#> 
#>     sd, var

y = tf_rgp(1)
names(y) = ""
#> Error: If any elements are named, all elements must be named.

x = tf_rgp(1)
names(x) = "x"

c(x, y)
#> Error: If any elements are named, all elements must be named.
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Right now, the empty names stuff is a bit of a hacky mess -- we'd been using `""` in a lot of places instead of leaving `NULL`, but we can avoid the errors above by just leaving `NULL`s for now, so that's what I've done in e.g. edb4e7e2e76219a1c2bca73849b0b3f1de78733b. 

For what it's worth, the folks at [`sf`](https://r-spatial.github.io/sf/) have avoided this by using functions in `vctrs` to control behaviors related to concatenation and casting of `sf` objects, but not actually make `sf` objects have class `vctrs_vctr`. MIght be an option to consider ... 

Also we can just wait a bit and see what the `vctrs` folks decide and update our dependency as needed.

**Comment by fabian-s** [comment]
see  #120
