### ISSUE TITLE
bracket outputs

### ISSUE THREAD

**Issue by jeff-goldsmith** [tidyfun/tidyfun#104]
not pressing at all, but belatedly realized that `[` sometimes returns a `tf` vector and sometimes returns a matrix, that i guess you can then convert back to a `tf` vector if you want:

``` r
library(tidyfun)
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2
#> 
#> Attaching package: 'tidyfun'
#> The following objects are masked from 'package:stats':
#> 
#>     sd, var

data(dti_df)

vec = dti_df$cca[1:5]
mat = dti_df$cca[1:5, seq(0, 1, l = 50), interpolate = TRUE]

class(vec)
#> [1] "tfd_irreg"  "tfd"        "tf"         "vctrs_vctr"
class(mat)
#> [1] "matrix"
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

this was clearly an intentional choice, but i'm not sure i understand the logic -- maybe we can discuss?

**Comment by fabian-s** [comment]
sure -- first argument to `[` selects which functions from the tf-vector to keep, simple subindexing.

`[` without a second arg always returns object of same type as entered.  

Second argument defines on which argument values to evaluate the functions. very easy way to evaluate/interpolate. return value then can be an array of function evaluations or a list of dataframes, one for each function, containing function evals as (arg, value)-pairs in each row.

seemed like a very convenient shorthand to allow for quickly evaluating functional data and getting back data suitable for further processing (arrays for modeling functions/base plots, list column with data.frames for tidyverse)

I like it and i'm gonna keep it, fight me :hocho: :skull: :hocho:

**Comment by jeff-goldsmith** [comment]
okay, okay ...

but also -- why wouldn't using two arguments also give a tf-vector evaluated over the new args? you can always turn that vector into a matrix or whatever

gotta say though the knife + skull + knife emojis have me shook rn

**Comment by fabian-s** [comment]
idea is to hide `arg`-related details from users as much as possible and have `tf`-objects behave as much like real functional data as possible.  

(in my head, i distinguish between objects that are functions (i.e, `tf`-objects) and objects that contain vectors of function evaluations (matrices, data.frame, etc), if that makes sense?)

also: supplying new argvals to `tf` object in basis representation would not make much sense -- why re-evaluate the basis functions on a different grid, that really should not change anything about the represented functions?

**Comment by jeff-goldsmith** [comment]
okay -- at least i see more what you mean. and this is consistent with `tf_evaluate` in a way i hadn't thought about. 

i suppose i'm thinking of "evaluate" as something more like "reevaluate" or "update args" -- some easy way to e.g. interpolate functional data over a new grid but keep them as functions. maybe we need a function that does that (`tf_interpolate`?). 

right now it seems like we're assuming that evaluating functions on a new grid means that you only want the vectors of function evaluations; keeping them as functions would require something like:

```
library(tidyfun)
library(dplyr)

grid <- seq(0, 1, l = 11)
a <- tf_rgp(3, arg = 7)
tf_evaluate(a, grid) %>% tfd(arg = grid)
```

i don't know which i'd be more likely to use in practice though. 

ANYWAY. the thing that really bothered me about this is that `[` returns objects with different classes depending on the number of arguments and that seems ... not entirely consistent with predictability as a design goal.

**Comment by fabian-s** [comment]
> some easy way to e.g. interpolate functional data over a new grid but keep them as functions.

That's `tfd(a, arg = grid)`. Seems easy enough? 
Good that you raised this point, this is a common operation that obviously needs to be more prominently documented. 

> the thing that really bothered me about this is that [ returns objects with different classes depending on the number of arguments and that seems ... not entirely consistent with predictability as a design goal.

Agreed. I broke predictability to get convenience here. 
@julia-wrobel is this bracket-notation stuff as weird for you as for Jeff? the people in my previous group seemed to like it, but maybe it was not a good choice.

**Comment by jeff-goldsmith** [comment]
> That's tfd(a, arg = grid). Seems easy enough?

Yeah, that's easy -- agreed we might want to make it a bit more clear in documentation, since I'd missed / forgotten. Also I'm wondering about e.g. `tf_interpolate` -- it would duplicate this functionality but be obvious to someone scanning function names. (Separate from the `[` stuff though.)

> Agreed. I broke predictability to get convenience here.

TBH I'm probably rarely going to use this, since I'm all-in on tibbles and almost never use `[` anyway -- so if you find it useful, I'll ignore the bit of unpredictability!

**Comment by fabian-s** [comment]
> Also I'm wondering about e.g. tf_interpolate -- it would duplicate this functionality but be obvious to someone scanning function names.

Good point, and for pipe workflows this is important, see #107. 
Can we close this here then?

**Comment by jeff-goldsmith** [comment]
Yup!
