### ISSUE TITLE
tf_nest .id parameter error

### ISSUE THREAD

**Issue by a-chernofsky** [tidyfun/tidyfun#109]
I am using the tf_nest() function to create a tf column in a data.frame with an .id parameter from a numeric id variable. I was  getting the following error:

"Error in `[.tf`(tfd_list[[v]], id_index, ) : Assertion on 'i' failed: Element 1 is not <= 3000."

After doing some digging into your source code, I figured out that the error was occurring because I was using a numeric id variable with values greater than the number of subjects. In the pigs example on the package website, the id column is also the index for the unique id, but the id column in my data was a random 5 digit number. I was able to circumvent the issue by converting the id variable to character.

**Comment by fabian-s** [comment]
thx @a-chernofsky  -- should be fixed now in the dev-branch, install with `remotes::install_github("tidyfun/tidyfun", ref = "dev")`
