### ISSUE TITLE
Is memoization useful?

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#119]
Evaluator functions save arguments and results of previous calls for improved speed at the cost of more memory. The more often a `tf`-object is evaluated on different args, the larger its memory footprint becomes, but repeated evaluation of a functional datum on the same args should be (almost) instantaneous: a look-up instead of a computation. 

For` tfd`,  evaluator function calls are simple and fast interpolations, specific to the individual curve (!).  

For `tfb`, re-evaluation of basis functions on new argument values is memoised, but not the actual vector-mat multiplications that yield the new function values. Memoisation here might be more useful than for tfd because the stuff in memory is not specific to an indiv. curve (basis is the same for all), or not helping at all because re-evaluating the basis might be cheap/quick compared to the vector-mat-mult.

I never actually tested whether this is actually useful in terms of speed and worth the increased memory (see #117, e.g.).  

TODO: set up time/memory benchmarks for

- [x] regular tfd 
- [ ] irregular tfd
- [x] tfb

**Comment by fabian-s** [comment]
``` r
devtools::load_all()
```

    ## ℹ Loading tidyfun

    ## Registered S3 method overwritten by 'GGally':
    ##   method from   
    ##   +.gg   ggplot2

``` r
library(rbenchmark)
library(profvis)
```

``` r
set.seed(1312)
n <- 100
g <- 1000
arg <- seq(0, 1, l = g)

tfd_lin <- tf_rgp(n = n, arg = arg) |> tfd(resolution = 1e-16)
tfd_sp <- tfd(tfd_lin, evaluator = tf_approx_spline)
tfd_const <- tfd(tfd_lin, evaluator = tf_approx_locf)

tfb_cr10 <- rep(tfb(tfd_lin, k = 10), times = 100)
```

    ## Percentage of input data variability preserved in basis representation
    ## (per functional observation, approximate):
    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##   98.40   99.80   99.90   99.79   99.90  100.00

``` r
tfb_tp10 <- rep(tfb(tfd_lin, k = 10, bs = "tp"), times = 100) 
```

    ## Percentage of input data variability preserved in basis representation
    ## (per functional observation, approximate):
    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##   98.40   99.78   99.90   99.78   99.90  100.00

``` r
tfb_cr50 <- rep(tfb(tfd_lin, k = 50), times = 100)  
```

    ## Percentage of input data variability preserved in basis representation
    ## (per functional observation, approximate):
    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##   98.40   99.80   99.90   99.79   99.90  100.00

``` r
tfb_ps50 <- rep(tfb(tfd_lin, k = 50, bs = "ps"), times = 100) 
```

    ## Percentage of input data variability preserved in basis representation
    ## (per functional observation, approximate):
    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##   98.40   99.80   99.90   99.79   99.90  100.00

``` r
tfb_tp50 <- rep(tfb(tfd_lin, k = 50, bs = "tp"), times = 100) 
```

    ## Percentage of input data variability preserved in basis representation
    ## (per functional observation, approximate):
    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##   98.40   99.80   99.90   99.79   99.90  100.00

``` r
domain <- tf_domain(tfd_lin)
rez <- tf_resolution(tfd_lin)
arg_new <- tfd_lin[1] |> tf_jiggle() |> tf_arg()
```

# “’ere be pointers!”-weirdness

``` r
f <- tfd_lin 
pryr::object_size(attr(f, "evaluator"))
```

    ## 494,936 B

``` r
bla <- tf_evaluate(f, arg_new)
pryr::object_size(attr(f, "evaluator"))
```

    ## 1,350,032 B

``` r
pryr::object_size(attr(tfd_lin, "evaluator"))
```

    ## 1,350,032 B

``` r
# evaluating `f` also changes `tfd_lin` -- their evaluator functions have
#     the same execution env holding the cache of previously used args and computed values:
identical(
  environment(attr(f, "evaluator")), 
  environment(attr(tfd_lin, "evaluator"))
)
```

    ## [1] TRUE

``` r
memoise::forget(attr(f, "evaluator"))
```

    ## [1] TRUE

``` r
pryr::object_size(attr(f, "evaluator"))
```

    ## 1,343,576 B

``` r
# !! forgetting/ resetting cache does not restore original object size at all. WTF.
```

# benchmark time/memory for tfb and tfd\_reg with/without memoization

## profiling: un-cached evaluation vs cached evalutatio

-   eval on never-seen-before grid and then once more on the same,
    cached grid
-   compare times, memory I/O, object sizes:

``` r
f <- tfd_const
memoise::forget(attr(f, "evaluator"))
pryr::object_size(attr(f, "evaluator"))

(p_no_memo <- profvis(tf_evaluate(f, arg = arg_new)))
pryr::object_size(attr(f, "evaluator"))

(p_memo <- profvis(tf_evaluate(f, arg = arg_new)))
memoise::forget(attr(f, "evaluator"))
pryr::object_size(attr(f, "evaluator"))
```

for `n  = 100, g = 1000`:

| f            | time (ms) | memory (MB)     | evaluator size (MB) |
|--------------|-----------|-----------------|---------------------|
| `tfd_lin:`   | 140 vs 40 | -0/+68 vs 0/+13 | 0.334 vs 1.175      |
| `tfd_sp:`    | 140 vs 50 | 0/+70 vs 0/+16  | 0.342 vs 1.183      |
| `tfd_const:` | 120 vs 50 | 0/+62 vs 0/+18  | 0.342 vs 1.184      |

``` r
f <- tfb_tp50
memoise::forget(attr(f, "basis"))
pryr::object_size(attr(f, "basis"))

(p_no_memo <- profvis(tf_evaluate(f, arg = arg_new)))
pryr::object_size(attr(f, "basis"))

(p_memo <- profvis(tf_evaluate(f, arg = arg_new)))
memoise::forget(attr(f, "basis"))
pryr::object_size(attr(f, "basis"))
```

for `n  = 1000, g = 1000` (`tfb` too fast for `n  = 100`!)

| f          | time (ms)       | memory (MB) | basis evaluator size (MB) |
|------------|-----------------|-------------|---------------------------|
| `tfb_cr10` | 120 vs 130 (!!) | 31 vs 31    | 3.835 vs 0.648 (!!)       |
| `tfb_cr50` | 110 vs 110      | 31 vs 27    | 4.224 vs 1.329 (!!)       |
| `tfb_ps50` | 120 vs 140 (!!) | 27 vs 30    | 4.22 vs 1.324 (!!)        |
| `tfb_tp50` | 180 vs 140      | 39 vs 31    | 4.61 vs 1.714 (!!)        |

# different method, same idea

``` r
eval_tfd <- function(f, arg = arg_new, reps = 20, memo = TRUE) {
  #evaluate and delete memoized result
  for(i in 1:reps) {
    f[, arg]
    if(!memo) memoise::forget(attr(f, "evaluator"))
  }
  memoise::forget(attr(f, "evaluator"))
  NULL
}  

memoise::forget(attr(tfd_lin, "evaluator"))
```

    ## [1] TRUE

``` r
bench::mark(
  no = eval_tfd(tfd_lin, memo = FALSE),
  yes =  eval_tfd(tfd_lin),
  iterations = 1
)
```

    ## Warning: Some expressions had a GC in every iteration; so filtering is disabled.

    ## # A tibble: 2 × 6
    ##   expression      min   median `itr/sec` mem_alloc `gc/sec`
    ##   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
    ## 1 no            2.97s    2.97s     0.337    1.48GB     6.07
    ## 2 yes         848.4ms  848.4ms     1.18   516.52MB     9.43

``` r
memoise::forget(attr(tfd_sp, "evaluator"))
```

    ## [1] TRUE

``` r
bench::mark(
  no = eval_tfd(tfd_sp, memo = FALSE),
  yes =  eval_tfd(tfd_sp),
  iterations = 1
)
```

    ## Warning: Some expressions had a GC in every iteration; so filtering is disabled.

    ## # A tibble: 2 × 6
    ##   expression      min   median `itr/sec` mem_alloc `gc/sec`
    ##   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
    ## 1 no            3.17s    3.17s     0.316    1.52GB     5.05
    ## 2 yes        759.27ms 759.27ms     1.32   518.82MB     3.95

``` r
memoise::forget(attr(tfd_const, "evaluator"))
```

    ## [1] TRUE

``` r
bench::mark(
  no = eval_tfd(tfd_const, memo = FALSE),
  yes =  eval_tfd(tfd_const),
  iterations = 1
)
```

    ## Warning: Some expressions had a GC in every iteration; so filtering is disabled.

    ## # A tibble: 2 × 6
    ##   expression      min   median `itr/sec` mem_alloc `gc/sec`
    ##   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
    ## 1 no            2.41s    2.41s     0.415    1.44GB     4.98
    ## 2 yes        729.56ms 729.56ms     1.37   514.59MB     5.48

`tfd`: fully memoized interpolation is

-   3x faster
-   3-4x times memory

``` r
eval_tfb <- function(f, arg = arg_new, reps = 20, memo = TRUE) {
  #evaluate and delete memoized result
  for(i in 1:reps) {
    f[, arg]
    if(!memo) memoise::forget(attr(f, "basis"))
  }
  memoise::forget(attr(f, "basis"))
  NULL
}  

memoise::forget(attr(tfb_cr10, "basis"))
```

    ## [1] TRUE

``` r
bench::mark(
  no = eval_tfb(tfb_cr10[1:n], memo = FALSE),
  yes =  eval_tfb(tfb_cr10[1:n]),
  iterations = 1
)
```

    ## Warning: Some expressions had a GC in every iteration; so filtering is disabled.

    ## # A tibble: 2 × 6
    ##   expression      min   median `itr/sec` mem_alloc `gc/sec`
    ##   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
    ## 1 no            158ms    158ms      6.35     107MB     6.35
    ## 2 yes           134ms    134ms      7.45     102MB     7.45

``` r
memoise::forget(attr(tfb_cr50[1:n], "basis"))
```

    ## [1] TRUE

``` r
bench::mark(
  no = eval_tfb(tfb_cr50[1:n], memo = FALSE),
  yes =  eval_tfb(tfb_cr50[1:n]),
  iterations = 1
)
```

    ## Warning: Some expressions had a GC in every iteration; so filtering is disabled.

    ## # A tibble: 2 × 6
    ##   expression      min   median `itr/sec` mem_alloc `gc/sec`
    ##   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
    ## 1 no            154ms    154ms      6.48     132MB     6.48
    ## 2 yes           547ms    547ms      1.83     110MB     3.65

``` r
memoise::forget(attr(tfb_ps50[1:n], "basis"))
```

    ## [1] TRUE

``` r
bench::mark(
  no = eval_tfb(tfb_ps50[1:n], memo = FALSE),
  yes =  eval_tfb(tfb_ps50[1:n]),
  iterations = 1
)
```

    ## Warning: Some expressions had a GC in every iteration; so filtering is disabled.

    ## # A tibble: 2 × 6
    ##   expression      min   median `itr/sec` mem_alloc `gc/sec`
    ##   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
    ## 1 no            147ms    147ms      6.80     128MB     0   
    ## 2 yes           142ms    142ms      7.02     109MB     7.02

``` r
memoise::forget(attr(tfb_tp10[1:n], "basis"))
```

    ## [1] TRUE

``` r
bench::mark(
  no = eval_tfb(tfb_tp10[1:n], memo = FALSE),
  yes =  eval_tfb(tfb_tp10[1:n]),
  iterations = 1
)
```

    ## Warning: Some expressions had a GC in every iteration; so filtering is disabled.

    ## # A tibble: 2 × 6
    ##   expression      min   median `itr/sec` mem_alloc `gc/sec`
    ##   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
    ## 1 no            418ms    418ms      2.39     112MB     2.39
    ## 2 yes           139ms    139ms      7.19     102MB     0

``` r
memoise::forget(attr(tfb_tp50[1:n], "basis"))
```

    ## [1] TRUE

``` r
bench::mark(
  no = eval_tfb(tfb_tp50[1:n], memo = FALSE),
  yes =  eval_tfb(tfb_tp50[1:n]),
  iterations = 1
)
```

    ## Warning: Some expressions had a GC in every iteration; so filtering is disabled.

    ## # A tibble: 2 × 6
    ##   expression      min   median `itr/sec` mem_alloc `gc/sec`
    ##   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
    ## 1 no            594ms    594ms      1.68     155MB     1.68
    ## 2 yes           159ms    159ms      6.30     111MB     0

`tfd`: fully memoized interpolation performance depends on *type* of
basis

-   small differences for “cr”, “ps”
-   for `tp`: &gt;2x faster (strongly depending on
    ![k](https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&space;%5Cbg_white&space;k "k")),
    for large
    ![k](https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&space;%5Cbg_white&space;k "k")
    50% more memory.

**Comment by fabian-s** [comment]
??

- is the speed up worth the added complexity, given the memory usage?
- how dangerous is: "different objects point to the same environment for look-up"?
- not understanding what determines the memory size of these look-up caches  -- why is the size increase after evaluating not reversible by forgetting the cached values?

**Comment by fabian-s** [comment]
still very unsure about this.
more tending towards "remove memoization" because "keep it simple"  & 3x faster evaluation is prob. not actually that relevant since it's already fairly fast in most cases.

@jeff-goldsmith what do you think?  do those benchmarks above even make sense?

**Comment by jeff-goldsmith** [comment]
I think that re-evaluating functions over new grids isn't something I do too often -- and evaluating over new grids in a way that would benefit from memoisation is probably something I do even less. so the speed benefits are nice but not usual that critical.

we don't currently have a ton of cases where the increased memory footprint is a problem, though -- the example in #117 shows that it exists, but i don't know if we can extrapolate from that to a setting where memory is going to be a problem.

all that to say -- on balance i would remove memoisation, but i'm not gonna get too bent out of shape until it becomes a more obvious issue.

**Comment by fabian-s** [comment]
yes, this was a stupid design decision. I'll remove it, more hassle than it's worth.

**Comment by fabian-s** [comment]
see attic/dev-119-memoisation-YESMEMO and attic/dev-119-memoisation-NOMEMO for benchmarks 

- repeated evals on identical grid *are* faster using memoisation (tfd: 3-5x, tfb very dependent on basis and basis size 1-6x), memory I/O fairly similar.
- evals on different grids are not (much) slower despite using memoisation -- the failed look-ups seem to not matter much.

still too complicated and weird and probably not worth it in realistic applications.

**Comment by fabian-s** [comment]
``` r
for (t in list.files("~/fda/tidyfun/tests/testthat", full.names = T)[-1]) {
   git2r::checkout(branch = "119-no-memo") #@975f15
   devtools::load_all()
   t_no <- replicate(10, 
                     system.time(
                        testthat::test_file(t, reporter = FailReporter)
                        )["elapsed"])
   git2r::checkout(branch = "dev") # @ba48336f
   devtools::load_all()
   t_yes <- replicate(10, 
                      system.time(
                         testthat::test_file(t, reporter = FailReporter)
                        )["elapsed"])
   cat(t, ":\n ") 
   print(summary(t_no/t_yes))
}
```

    ## ℹ Loading tidyfun

    ## Registered S3 method overwritten by 'GGally':
    ##   method from   
    ##   +.gg   ggplot2

    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-calculus.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.6133  0.8127  0.8870  0.8895  0.9182  1.3786

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-depth.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.5657  0.8022  0.9312  1.0249  1.3296  1.5928

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-evaluate.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.8678  0.9344  0.9830  0.9797  1.0331  1.0868

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-evaluator.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.2709  0.2781  0.2819  0.2881  0.2964  0.3171

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-names.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.7464  0.9313  0.9782  0.9821  1.0110  1.3261

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-ops.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.7447  0.8047  0.9272  0.9395  1.0452  1.2632

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-tfb-fpc.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.8640  0.9566  0.9937  0.9922  1.0166  1.1048

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-tfb-spline.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.5532  0.6370  0.6850  0.6888  0.7454  0.8679

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-tidyr.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.5333  0.7453  0.8029  0.8239  0.8695  1.1187

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-vctrs.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.9972  1.0709  1.1101  1.1483  1.1439  1.4629

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-where.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.6612  0.7960  0.9258  0.9279  0.9982  1.3087

    ## ℹ Loading tidyfun
    ## ℹ Loading tidyfun

    ## /home/fabians/fda/tidyfun/tests/testthat/test-zoom.R :
    ##     Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##  0.8233  0.9841  1.0955  1.0974  1.1972  1.4180


--> no relevant slow-downs in the tests. test-evaluator and test-tfb-spline improved
