### ISSUE TITLE
need new website / online documentation after package split

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#123]
splitting tidyfun into several parts (#69) means we need to overhaul the pkgdown site.

most core functionality will be in `tf`, so simply having a pkgdown site for `tidyfun` won't work anymore -- wouldn't have most of the important help pages.

things we could try:

- separate pkgdown sites for each package, preferably with lots of cross linking between them. 
  +:  as easy to maintain as now. 
  -: much more difficult to navigate & confusing for users who don't need to be aware of underlying package structure. might be hard to keep cross-links from deteriorating over time

   could also be separate pkgdown sites for each package under a common blogdown site:   e.g. https://conorneilson.com/post/integrating-blogdown-and-pkgdown/

  
- use pkgdown to create html from `tf`, `tidyfun` (and  forthcoming packages in the family), copy those to some separate ""website"-repo, cobble them together manually
  +: could create a website that looks like what we have now. potentially very customizable. could take vignettes out of the packages and make them as big and as many as we want withoput worrying about CRAN compilation times.
  -: too hard, too fragile. unlikely that automatically generated HTML/md from pkgdown will be useable like this.
  
 - create a dummy documentation package without code that just gets copies of all the help files and vignettes and run pkgdown on that
 +: would create a website that looks like what we have now. fairly easy to update.
 - : unlikely that automatically generated HTML/md from package code in different packages will be useable like this directly.

other ideas @jeff-goldsmith?

**Comment by jeff-goldsmith** [comment]
our eventual goal is that most users will install `tidyfun` without worrying about the backend, right? sort of like you install / load `tidyverse` and mostly don't worry about what comes from `dplyr` vs `tidyr`...?

or will there be a different package name that installs / loads `tf`, `ggtf`, and `tidyfun`? maybe `tidyfun` is the umbrella and we rename the third package? (i sort of like this, so that later packages like `refundr` could be added to the family...)

i'm asking because in general i'd think some broadly useful vignettes would sit wherever the umbrella package can be found, with more targeted pages for each package. for example, we might show how you get matrix data into a `tf` vector, and get that in a tibble, and do some manipulation and plotting -- and then give links to the individual packages that define operations more carefully.

 this is most similar to option 1, i think, just trying to map out the user-facing process now.

**Comment by fabian-s** [comment]
> our eventual goal is that most users will install tidyfun without worrying about the backend, right? sort of like you install / load tidyverse and mostly don't worry about what comes from dplyr vs tidyr...?

yes

> or will there be a different package name that installs / loads tf, ggtf, and tidyfun? maybe tidyfun is the umbrella and we rename the third package? (i sort of like this, so that later packages like refundr could be added to the family...) 

i always assumed `refundr` would accept/return `tf`-inputs and rely on `tf`, but not necessarily require or be part of `tidyfun`? 

the split could be

- `tf` with the classes and methods for `tf[d|b]` vectors and minimal dependencies
- `tidyfun` with all the tidyverse-dependent wrangling and ggplot-based viz (this actually becomes a fairly small package with maybe a dozen exported functions) 
- additional packages like refundr for modelling, registr (eventually) for  registration, maybe `tf.wavelet` for wavelet things, other specialized packages for specific types of functional data, etc would mostly depend on `tf`, but not necessarily on `tidyfun`?
 
> i'm asking because in general i'd think some broadly useful vignettes would sit wherever the umbrella package can be found,

yes, agree. 

> with more targeted pages for each package.

yes, agree again -- e.g. we should move the "note to developers" vignette to `tf` and i need to add more details on the implementation details and how to write extensions etc there.

**Comment by jeff-goldsmith** [comment]
great! 

so the thinking is:
* move "`tf` vectors and operations" and "note to developers" to the `tf` page
* keep "data wrangling" and "visualization" with `tidyfun`
* add some cross referencing / short reviews of relevant stuff to both

what do you think about "converting data to and from `tf`"? seems more closely tied to the `tf` package, but something users starting with `tidyfun` will care about at least as much (if not more).

**Comment by fabian-s** [comment]
I  think I'd actually leave both "tf vectors and operations" and "converting data to and from tf" on the tidyfun page, for the reason you give: it's very important info for *users*, and we would want the tidyfun page to be the URL where all that can be found-
the gory technical details relevant for *developers* we can document on a separate `tf` page, and just link to the vignettes of `tidyfun` that are mostly `tf`-vignettes from there?


also finally found an example for somebody organising their package family with an "umbrella"- or meta-package structure: 

https://community.rstudio.com/t/re-export-all-objects-from-a-package/4295/4?u=fabian-s
https://github.com/forestgeo
https://forestgeo.github.io/fgeo/

**Comment by fabian-s** [comment]
alternatively: 
finally found an example for somebody organising their package family with an "umbrella"- or meta-package structure: 

https://community.rstudio.com/t/re-export-all-objects-from-a-package/4295/4?u=fabian-s
https://github.com/forestgeo
https://forestgeo.github.io/fgeo/
(maybe all we'd need to build an actual "umbrella" site and still keep packages small and thematically consistent is this: https://github.com/maurolepore/pkgdoc, c.f https://github.com/forestgeo/fgeo/blob/master/vignettes/siteonly/reference.Rmd)

**Comment by jeff-goldsmith** [comment]
if we're going to have two packages post-conscious-decoupling, i'd say a lot of documentation in `tidyfun` and some nitty-gritty in `tf` would work -- most users would install and reference the `tidyfun` stuff, and we'd be good to go. 

if we're going to have three+ packages (e.g. `tf`, `tf.plot`, `tf.wrangle`, `tf.wave` ...) under a `tidyfun` umbrella, following the `fgeo` route looks good -- most stuff under the umbrella page, with short documentation for each individual package.

**Comment by fabian-s** [comment]
I'm leaning towards "two packages" (for now), but that's not a very strong preference. wbu? 

**+**:

- most benefits of separate packages already present for two packages  (tf for low-level, slow changing, few-dependencies developer-oriented stuff safe to put on CRAN without too much hassle and tidyfun for dependency-heavy and "user interface" stuff with focus on accessible docs)
- documentation for 2 packages easier to navigate  
- less maintenance for us
- fewer namespace issues (e.g. whether to export or not internal utility functions for other tf-packages etc) 
- (still possible to separate out different parts of tidyfun later if it becomes too unwieldy, like we did with tf)

**-**:

- (much) harder to recruit/onboard collaborators to work on one part of a large package  (NB: "tidyfun minus tf" is actually fairly small rn....) than add/improve a small package with narrow focus. 
- messier packages


what else should we consider?

**Comment by fabian-s** [comment]
things that seem feasible:

- tidyfun reexports *all* tf functions, pkgdown page for tidyfun links to tf's pkgdown-page (https://community.rstudio.com/t/best-practices-for-documenting-re-exports/89254)
*+: fully automated web site generation.  
-: rather bad UI*

- tidyfun reexports *all* tf functions. generate html-doc files for tf with pkgdown, copy them into appropriate folder for tidyfun's pkgdown page (https://github.com/r-lib/pkgdown/issues/715 maybe ?) and edit `_pkgdown.yml` so we show the actual help pages instead of a single `reexports.html` with links to `tf`.  
*+: possible to automate with scripts / makefiles (?), single website easy to search/browse.  
-: harder to keep stuff in sync -- every update to tf must trigger update to tidyfun website as well. automation likely to break as pkgdown evolves*  

- same as above but don't copy html from tf gh-pages to tidyfun gh-pages and just insert direct links to tf gh-pages from tidyfun gh-pages site. 

- make umbrella site using https://github.com/maurolepore/pkgdoc, see https://github.com/forestgeo/fgeo/blob/master/vignettes/siteonly/reference.Rmd  
*+: exactly right tool for the job -- no need to work around pkgdown's intended scope. easy to scale if tidyfun framework expands to more than 2 packages.  
-:  pkgdoc repo not updated in 3yrs, not on CRAN & dormant (?)*


@jeff-goldsmith @julia-wrobel thoughts/ideas ?
