### ISSUE TITLE
create tidyfun data package / tidyfun data github repository 

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#130]
- DTI
- accelerometry

Jeff might be able to provide

- reaching data
- process firing rate data

FS:

- ABR curves from GMC
- ask Moritz about bodyweight fitness data set

- prep a "benign" weather/climate dataset & do a case study on that shopwing data preprocessing, data viz, wrangling: use {rnoaa}

**Comment by m-muecke** [comment]
@fabian-s can you create a new repo, then I will take care of this

**Comment by fabian-s** [comment]
nice! 

here it is: https://github.com/tidyfun/tidyfundata

**Comment by m-muecke** [comment]
> nice!
> 
> here it is: https://github.com/tidyfun/tidyfundata

@fabian-s Probably can be closed
