### ISSUE TITLE
methods for registering functional data

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#18]
first stage: 

i.e., apply given warping functions to fvector objects.

`register(fvector, warping)`

gives you back an `fvector` of registered functions. 

2nd stage:  write a wrapper function for Julia's registering algos / `fdasrvf` / whatever.

**Comment by jeff-goldsmith** [comment]
i don't know how or when warping functions will be given without a registration step, and i guess i'd think that registration is more of a "method" that should exist in another package (e.g. `registr` or `refund`). 

what about this as a workflow:

```
warping_fit = fun_df %>%
  registr::registr(., funs)

fun_df %>%
  mutate(aligned_funs = tf_align(funs, warping_fit))
```

this is basically what you suggested, i think, but makes it more explicit where warping functions will come from. and honestly, i don't know if i love this workflow. an alternative might be:

```
fun_df %>%
  add_aligned(warping_fit) %>%
  add_warpings(warping_fit)
```

(this would include both aligned functions and add an feval of the warping functions themselves)

**Comment by fabian-s** [comment]
jeff says: modeling, not exploring. out of scope. 

@julia-wrobel : at some point we would like to see `registr` return tf objects. nudge nudge wink wink
