### ISSUE TITLE
rename ggplot geoms

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#61]
... ? 
the pasta theme is/was funny to me, but maybe we should turn this into something more serious and descriptive:

`geom_spaghetti -> geom_tf_line`   (`geom_hairball`, more fittingly)  
 `geom_cappelini -> geom_tf_glyphs`  
 `gglasagna` could stay, I guess? maybe get an alias `tf_lasagnaplot`? or `tf_heatmap`?  
for the functional boxplot i was going for `geom_pappardelle`, the grown-up version of that would 
`geom_tf_boxplot`, i guess.

@jeff-goldsmith , what do you think?

**Comment by jeff-goldsmith** [comment]
i think "spaghetti plots" are well established enough that we can use `geom_spaghetti`; that's nearly true for "lasagna plots" too. 

personally, i like the pasta theme and don't mind sticking with it. i guess we could have boring aliases for these functions for boring users, but i wouldn't advocate becoming boring people with a boring package in general!
