### ISSUE TITLE
switch to vctrs-style S3 classes once that is used in dplyr  / tidyverse consistently

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#65]
the `vctrs`-package seems to be maturing and the way to go to solve issues like #62, #53, and also to make `c`, Ops and Maths functions more robust/reliable especcially when mixing irregular and regular `tf`s.

[This comment](https://github.com/tidyverse/dplyr/issues/3695#issuecomment-426027509)  seems  to indicate this can wait for `dplyr` 0.9 series

**Comment by jeff-goldsmith** [comment]
Looks like we might be forced to resolve this -- `vctrs` is now a thing, and a bunch of `tidyverse` stuff is being stricter about inputs being "vectors".

As a quick example, this used to work and now doesn't:

```
dti_df %>% 
  filter(case == "control")
```

@fabian-s -- do you understand how `vctrs` is supposed to solve all our problems?

**Comment by fabian-s** [comment]
:man_shrugging: the only thing I know is it's going to create a lot of new problems. let's hope it also solves some old ones.  I won't be able to work on this for a while, sorry.

**Comment by jeff-goldsmith** [comment]
A variety of commits up to and including 0fad1fc78a59d33b99079b41f0aa4914eca83d9b introduced `vctrs` into `tidyfun`. 

This was prompted by recently-broken tidyverse stuff -- with new versions of `tidyr`, `dplyr` and others, you could no longer work with `tf` vectors. Switching to `vctrs` didn't automatically fix anything, as far as I can tell, but at least now everything that used to work still works. I'm going to close this, and open a couple of related issues that are more specific about `vctrs` issues.
