### ISSUE TITLE
spread/gather -> pivot_wide/pivot_long

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#78]
create synonyms / replace  -- see https://tidyr.tidyverse.org/dev/articles/pivot.html

**Comment by jeff-goldsmith** [comment]
I'm not sure this switch makes a ton of sense for `tidyfun` -- `gather` as a "verb" meaning "wide to long" never made a ton of sense, but `tf_gather` as a "verb" meaning "wide to narrow" seems like a better fit. I'd make a similar case for `spread` and `tf_spread`.

If `spread` / `gather` are being dropped, maybe we need functions that don't map exactly onto `tidyr` functions?

**Comment by fabian-s** [comment]
spread/gather are "retired", i.e. "superseded", not "deprecated".
 
so I guess we can just keep them cause the tibblyversers promised to keep maintaining them.
