### ISSUE TITLE
Wavelets: non-dyadic n

### ISSUE THREAD

**Issue by SvenLorenz** [tidyfun/tidyfun#90]
Implementations for wavelets normally only take inputs of length 2^J, this is obviously not a given with real world data. Current solution would be to add data to the input to make it 2^J. Example:
```r
library(wavethresh)
y <- c(2,4,5,3,1)
length(y) # 5
# Error
ywd <- wd(y)

y_pad <- c(2,2,2,4,5,3,1,1)
length(y_pad) # 8
ywd <- wd(y_pad)
```

Better solutions might be found in the future.

**Comment by SvenLorenz** [comment]
[On preconditioning the data for the wavelet transform when the sample size is not a power of two (Ogden 1997)](https://www-tandfonline-com.emedien.ub.uni-muenchen.de/doi/abs/10.1080/03610919708813391):

Introduces several methods for dealing with non dyadic data length.

Extending:
* dilutes coefficients at the borders
 -> Interpretation of coefficients change
 -> Border coefficients have wrong variance
* Problems remain regardless of n
* easiest to implement
* least computationally expensive
* different versions of extending

Interpolation:
* Variance is bigger than normal
* correlation between adjacent observations
* easy to implement
* O(n)

Integration:
* computationally expensive (so probably not our favored approach)

Threshold methods depend on certain assumptions these methods violate!

**Comment by SvenLorenz** [comment]
```r
set.seed(1234)
f <- function(t) 2*t + dbeta(t, 5, 7) * ifelse(t < .5, -1, 1) - .2 * dnorm(t, 0.2, 0.05)

t <- seq(0, 1, l = 2^10 - 100)
y <- f(t) + rnorm(length(t), sd = .5)

## Simple Zero padding
y <- wavelets::extend.series(y, method = "zeros", length = "powerof2", j = 10)

y_t <- remove_slope(1:1024, y)

Z <- cbind(1, ZDaub(1:2^10, numLevels = 6))
## weigh the padded observerations with 0 
wt <- c(rep(1, 924), rep(0, 100))

coef_qr <- lsfit(Z, y_t, wt = wt, intercept = FALSE)$coef
yhat <- cbind(Z, attr(y_t, "slope")) %*% c(coef_qr, 1)

plot(y, pch = 20, cex = .1)
lines(yhat, col = "orange", lwd = 2)
```

![Zero Padding](https://user-images.githubusercontent.com/43496748/68997506-ad672480-08a7-11ea-93e8-56db14381bcb.jpeg)

If i understood correctly this was the weighted least squares approach. It fits the padded data very bizzarly, but the actual data is pretty well fitted. I am however not 100% sure this is what you meant with the weighted least squares. 
Also `remove_slope` doesn't change the estimation too much.

**Comment by fabian-s** [comment]
Yes, that's roughly what I meant. Simply dropping the 0-weighted padding pseudo-observations is more efficient, though, adding to your code above:

```
padding <- 925:1024
coef_qr2 <- lsfit(Z[-padding, ], y_t[-padding], intercept = FALSE)$coef
all.equal(coef_qr2, coef_qr)
# TRUE
lines(cbind(Z, attr(y_t, "slope")) %*% c(coef_qr2, 1), col = "red",
      lty = 2)
```
![image](https://user-images.githubusercontent.com/998541/69051750-8c1c4a80-0a05-11ea-9675-6b431e5ad6f4.png)
